dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.CommandBox
notifications:
  email: false
addons:
  ssh_known_hosts: twd.initzero.net
before_install:
- wget http://downloads.ortussolutions.com/ortussolutions/commandbox/3.8.0/commandbox-bin-3.8.0.zip
  -O /tmp/commandbox.zip
- unzip /tmp/commandbox.zip
install:
- ./box install
before_script:
- ./box server start port=8500
script:
- ./box testbox run runner='http://127.0.0.1:8500/tests/runner.cfm'
before_deploy:
- openssl aes-256-cbc -K $encrypted_75f3180c243e_key -iv $encrypted_75f3180c243e_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet --exclude '.dpl' --exclude 'box.json' --exclude '.CFConfig.json.tmpl' --exclude 'deploy_rsa.enc' --exclude 'deploy.sh' --exclude '.git' --exclude '.gitattributes' --exclude '.gitignore' --exclude 'README.md' --exclude 'server.json' --exclude '.travis.yml'  $TRAVIS_BUILD_DIR/ root@twd.initzero.net:/var/www/html/
  on:
    branch: master
